apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-producer-job
spec:
  template:
    spec:
      containers:
      - name: kafka
        image: solsson/kafka:0.11.0.0
        command: ["/bin/bash"]
        args: ["-c", " for i in {1..{{ .Values.message_number }}}; do shuf -zer -n{{ .Values.message_length }}  {A..Z} {a..z} {0..9} | ./bin/kafka-console-producer.sh --broker-list {{ .Values.kafka_cluster.host }}:{{ .Values.kafka_cluster.port }} --topic {{ .Values.topic }}; done"]
      restartPolicy: Never
